#General settings
[general]
	#modpackProjectID is now deprecated and will be removed soon
	# Default: 0
	# Range: > 0
	modpackProjectID = 0
	#The name of the modpack
	modpackName = "WorkLoad"
	#The version of the modpack
	modpackVersion = "Beta 1.21.1-2.0.10"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false
